import { SeedGuideQuestion } from './seed-types';

export const GUIDE_QUESTIONS: SeedGuideQuestion[] = [
  {
    guideId: 'wudu',
    question: 'Abdestte yüz kaç kere yıkanır?',
    options: ['Bir kere', 'Beş kere', 'İki kere', 'Üç kere'],
    correctAnswer: 'Üç kere',
    difficulty: 1,
  },
  {
    guideId: 'wudu',
    question: 'Abdeste başlarken hangi bölge yıkanır?',
    options: ['Eller', 'Yüz', 'Ayaklar', 'Kollar'],
    correctAnswer: 'Eller',
    difficulty: 1,
  },
  {
    guideId: 'wudu',
    question: 'Abdestin farzlarından biri aşağıdakilerden hangisidir?',
    options: ['Ağzı çalkalamak', 'Boynu meshetmek', 'Başa mesh etmek', 'Kulakları meshetmek'],
    correctAnswer: 'Başa mesh etmek',
    difficulty: 2,
  },
  {
    guideId: 'wudu',
    question: 'Kollar nereye kadar yıkanır?',
    options: [
      'Sadece bileklere kadar',
      'Omuzlara kadar',
      'Dirseklerle birlikte',
      'Parmak uçlarına kadar',
    ],
    correctAnswer: 'Dirseklerle birlikte',
    difficulty: 1,
  },
  {
    guideId: 'wudu',
    question: 'Ayaklar nereye kadar yıkanır?',
    options: ['Sadece parmaklar', 'Sadece tabanlar', 'Topuklarla birlikte', 'Dizlere kadar'],
    correctAnswer: 'Topuklarla birlikte',
    difficulty: 1,
  },
  {
    guideId: 'wudu',
    question: 'Ağzı su ile çalkalamaya ne ad verilir?',
    options: ['Mesh', 'Mazmaza', 'Tertip', 'İstinşak'],
    correctAnswer: 'Mazmaza',
    difficulty: 3,
  },
  {
    guideId: 'wudu',
    question: 'Burna su çekip temizlemeye ne ad verilir?',
    options: ['Muvâlât', 'Delk', 'Mazmaza', 'İstinşak'],
    correctAnswer: 'İstinşak',
    difficulty: 3,
  },
  {
    guideId: 'wudu',
    question: 'Abdest alırken organları sırayla yıkamaya ne denir?',
    options: ['Mesh', 'Tertip', 'İsraf', 'Niyet'],
    correctAnswer: 'Tertip',
    difficulty: 2,
  },
  {
    guideId: 'ghusl',
    question: 'Gusül abdestinin farzlarından biri aşağıdakilerden hangisidir?',
    options: [
      'Sadece kolları yıkamak',
      'Başı meshetmek',
      'Ayakları meshetmek',
      'Bütün bedeni yıkamak',
    ],
    correctAnswer: 'Bütün bedeni yıkamak',
    difficulty: 1,
  },
  {
    guideId: 'ghusl',
    question: 'Gusülde ağzın çalkalanması hangi mezhepte farz sayılır?',
    options: ['Şâfiî', 'Hiçbiri', 'Hanefî', 'Mâlikî'],
    correctAnswer: 'Hanefî',
    difficulty: 3,
  },
  {
    guideId: 'ghusl',
    question: 'Gusül alan kişi ayrıca abdest almalı mıdır?',
    options: [
      'Hayır, gusül abdest yerine geçer',
      'Evet, mutlaka almalıdır',
      'Sadece namaz kılacaksa almalıdır',
      'Sadece cuma günü almalıdır',
    ],
    correctAnswer: 'Hayır, gusül abdest yerine geçer',
    difficulty: 2,
  },
  {
    guideId: 'ghusl',
    question: 'Gusülde vücutta kuru yer kalırsa ne yapılır?',
    options: ['Gusül baştan alınır', 'Sadece mesh edilir', 'O yer yıkanır', 'Bir şey gerekmez'],
    correctAnswer: 'O yer yıkanır',
    difficulty: 2,
  },
  {
    guideId: 'ghusl',
    question: 'Gusle başlarken hangi davranış sünnettir?',
    options: [
      'Önce ayakları yıkamak',
      'Suyu ısıtmak',
      'Doğrudan başa su dökmek',
      'Besmele çekip elleri yıkamak',
    ],
    correctAnswer: 'Besmele çekip elleri yıkamak',
    difficulty: 2,
  },
  {
    guideId: 'ghusl',
    question: 'Gusül abdesti hangi durumda gerekir?',
    options: ['Yemek yiyince', 'Cünüplük hâlinde', 'Yolculuğa çıkınca', 'Uykudan uyanınca'],
    correctAnswer: 'Cünüplük hâlinde',
    difficulty: 1,
  },
  {
    guideId: 'ghusl',
    question: 'Gusülde saç diplerine su ulaştırmak gerekir mi?',
    options: [
      'Sadece erkekler için gerekir',
      'Hayır, gerekmez',
      'Evet, gereklidir',
      'Sadece kısa saçta gerekir',
    ],
    correctAnswer: 'Evet, gereklidir',
    difficulty: 2,
  },
  {
    guideId: 'ghusl',
    question: 'Gusül suyunu israf etmek hakkında hüküm nedir?',
    options: ['Gusül için şarttır', 'Hoş görülmemiştir', 'Tavsiye edilmiştir', 'Bir hükmü yoktur'],
    correctAnswer: 'Hoş görülmemiştir',
    difficulty: 2,
  },
  {
    guideId: 'fajr',
    question: 'Sabah namazının farzı kaç rekattır?',
    options: ['3 rekat', '1 rekat', '2 rekat', '4 rekat'],
    correctAnswer: '2 rekat',
    difficulty: 1,
  },
  {
    guideId: 'fajr',
    question: 'Sabah namazının farzından önce kaç rekat sünnet kılınır?',
    options: ['3 rekat', '4 rekat', 'Sünnet yoktur', '2 rekat'],
    correctAnswer: '2 rekat',
    difficulty: 1,
  },
  {
    guideId: 'fajr',
    question: 'Sabah namazında kıraat nasıl yapılır?',
    options: ['Yalnız cemaat sesli', 'Yalnız Fatiha sesli', 'Sessiz olarak', 'Sesli olarak'],
    correctAnswer: 'Sesli olarak',
    difficulty: 1,
  },
  {
    guideId: 'fajr',
    question: 'Sabah namazının vakti ne zaman biter?',
    options: ['Güneş doğunca', 'Kuşluk bitince', 'Öğle olunca', 'İkindi girince'],
    correctAnswer: 'Güneş doğunca',
    difficulty: 1,
  },
  {
    guideId: 'fajr',
    question: 'Sabah namazının vakti hangi olayla başlar?',
    options: [
      'Fecr-i sâdık ile',
      'Güneşin doğuşu ile',
      'Şafağın kaybolması ile',
      'Gece yarısı ile',
    ],
    correctAnswer: 'Fecr-i sâdık ile',
    difficulty: 2,
  },
  {
    guideId: 'fajr',
    question: 'Sabah namazının farzında kaç oturuş vardır?',
    options: ['2 oturuş', '1 oturuş', 'Oturuş yoktur', '3 oturuş'],
    correctAnswer: '1 oturuş',
    difficulty: 2,
  },
  {
    guideId: 'fajr',
    question: 'Sabah ezanına eklenen özel cümle hangisidir?',
    options: ['Haydi kurtuluşa', 'Namaz uykudan hayırlıdır', 'Allah en büyüktür', 'Namaz başladı'],
    correctAnswer: 'Namaz uykudan hayırlıdır',
    difficulty: 2,
  },
  {
    guideId: 'fajr',
    question: 'Sabah namazından sonra güneş doğana kadar nafile kılmak nasıldır?',
    options: ['Müstehaptır', 'Farzdır', 'Mekruhtur', 'Vaciptir'],
    correctAnswer: 'Mekruhtur',
    difficulty: 3,
  },
  {
    guideId: 'dhuhr',
    question: 'Öğle namazının farzı kaç rekattır?',
    options: ['4 rekat', '6 rekat', '3 rekat', '2 rekat'],
    correctAnswer: '4 rekat',
    difficulty: 1,
  },
  {
    guideId: 'dhuhr',
    question: 'Öğle namazı sünnetlerle birlikte toplam kaç rekattır?',
    options: ['6 rekat', '12 rekat', '10 rekat', '8 rekat'],
    correctAnswer: '10 rekat',
    difficulty: 2,
  },
  {
    guideId: 'dhuhr',
    question: 'Öğle namazında kıraat nasıl yapılır?',
    options: ['Son iki rekat sesli', 'Sesli olarak', 'İlk iki rekat sesli', 'Sessiz olarak'],
    correctAnswer: 'Sessiz olarak',
    difficulty: 1,
  },
  {
    guideId: 'dhuhr',
    question: 'Öğle vakti ne zaman başlar?',
    options: [
      'Şafak kaybolunca',
      'Güneş tepeden batıya kayınca',
      'Gölge iki katı olunca',
      'Güneş doğunca',
    ],
    correctAnswer: 'Güneş tepeden batıya kayınca',
    difficulty: 2,
  },
  {
    guideId: 'dhuhr',
    question: 'Öğle namazının farzından önce kaç rekat sünnet kılınır?',
    options: ['3 rekat', '4 rekat', 'Sünnet yoktur', '2 rekat'],
    correctAnswer: '4 rekat',
    difficulty: 1,
  },
  {
    guideId: 'dhuhr',
    question: 'Öğle namazının farzından sonra kaç rekat sünnet kılınır?',
    options: ['4 rekat', '2 rekat', 'Sünnet yoktur', '6 rekat'],
    correctAnswer: '2 rekat',
    difficulty: 1,
  },
  {
    guideId: 'dhuhr',
    question: 'Seferî kişi öğle farzını kaç rekat kılar?',
    options: ['1 rekat', '4 rekat', '3 rekat', '2 rekat'],
    correctAnswer: '2 rekat',
    difficulty: 2,
  },
  {
    guideId: 'dhuhr',
    question: 'Öğle farzının son iki rekatında zammı sure okunur mu?',
    options: [
      'Yalnız zammı sure okunur',
      'Okunmaz, yalnız Fatiha okunur',
      'Okunur, Fatiha ile birlikte',
      'Hiçbir şey okunmaz',
    ],
    correctAnswer: 'Okunmaz, yalnız Fatiha okunur',
    difficulty: 2,
  },
  {
    guideId: 'asr',
    question: 'İkindi namazının farzı kaç rekattır?',
    options: ['4 rekat', '6 rekat', '3 rekat', '2 rekat'],
    correctAnswer: '4 rekat',
    difficulty: 1,
  },
  {
    guideId: 'asr',
    question: 'İkindi namazının farzından sonra sünnet kılınır mı?',
    options: ['4 rekat kılınır', '6 rekat kılınır', '2 rekat kılınır', 'Kılınmaz'],
    correctAnswer: 'Kılınmaz',
    difficulty: 2,
  },
  {
    guideId: 'asr',
    question: 'İkindi namazında kıraat nasıl yapılır?',
    options: ['Sessiz olarak', 'İlk iki rekat sesli', 'Son rekat sesli', 'Sesli olarak'],
    correctAnswer: 'Sessiz olarak',
    difficulty: 1,
  },
  {
    guideId: 'asr',
    question: 'İkindi vakti ne zaman sona erer?',
    options: ['Güneş batınca', 'Gece yarısı olunca', 'Güneş tepeye gelince', 'Şafak kaybolunca'],
    correctAnswer: 'Güneş batınca',
    difficulty: 1,
  },
  {
    guideId: 'asr',
    question: 'İkindinin ilk sünneti hangi türdendir?',
    options: ['Farz', 'Gayr-i müekked sünnet', 'Müekked sünnet', 'Vacip'],
    correctAnswer: 'Gayr-i müekked sünnet',
    difficulty: 3,
  },
  {
    guideId: 'asr',
    question: 'Güneş sararmaya başladığında ikindi kılmak nasıldır?',
    options: ['Müstehaptır', 'Sünnettir', 'Vaciptir', 'Mekruhtur'],
    correctAnswer: 'Mekruhtur',
    difficulty: 3,
  },
  {
    guideId: 'asr',
    question: 'Seferî kişi ikindi farzını kaç rekat kılar?',
    options: ['1 rekat', '2 rekat', '4 rekat', '3 rekat'],
    correctAnswer: '2 rekat',
    difficulty: 2,
  },
  {
    guideId: 'asr',
    question: 'İkindi namazını kaçıran kişi ne yapar?',
    options: ['Sorumluluğu düşer', 'Sünnetini kılar', 'Yatsıya ekler', 'Kaza eder'],
    correctAnswer: 'Kaza eder',
    difficulty: 1,
  },
  {
    guideId: 'maghrib',
    question: 'Akşam namazının farzı kaç rekattır?',
    options: ['2 rekat', '3 rekat', '5 rekat', '4 rekat'],
    correctAnswer: '3 rekat',
    difficulty: 1,
  },
  {
    guideId: 'maghrib',
    question: 'Akşam namazının farzından sonra kaç rekat sünnet kılınır?',
    options: ['4 rekat', '3 rekat', '2 rekat', 'Sünnet yoktur'],
    correctAnswer: '2 rekat',
    difficulty: 1,
  },
  {
    guideId: 'maghrib',
    question: 'Akşam namazında kıraat nasıl yapılır?',
    options: ['İlk iki rekat sesli', 'Yalnız son rekat sesli', 'Tamamı sessiz', 'Tamamı sesli'],
    correctAnswer: 'İlk iki rekat sesli',
    difficulty: 2,
  },
  {
    guideId: 'maghrib',
    question: 'Akşam vakti ne zaman başlar?',
    options: ['Güneş sararınca', 'Gece yarısı olunca', 'Şafak kaybolunca', 'Güneş batınca'],
    correctAnswer: 'Güneş batınca',
    difficulty: 1,
  },
  {
    guideId: 'maghrib',
    question: 'Akşam vakti ne zaman sona erer?',
    options: ['Şafak kaybolunca', 'Güneş doğunca', 'İmsak girince', 'Gece yarısı olunca'],
    correctAnswer: 'Şafak kaybolunca',
    difficulty: 2,
  },
  {
    guideId: 'maghrib',
    question: 'Akşam namazında kaç oturuş vardır?',
    options: ['3 oturuş', 'Oturuş yoktur', '1 oturuş', '2 oturuş'],
    correctAnswer: '2 oturuş',
    difficulty: 2,
  },
  {
    guideId: 'maghrib',
    question: 'Seferî kişi akşam farzını kaç rekat kılar?',
    options: ['3 rekat', '1 rekat', '4 rekat', '2 rekat'],
    correctAnswer: '3 rekat',
    difficulty: 2,
  },
  {
    guideId: 'maghrib',
    question: 'Akşam namazını sebepsiz geciktirmek nasıldır?',
    options: ['Hoş görülmemiştir', 'Sünnettir', 'Tavsiye edilmiştir', 'Vaciptir'],
    correctAnswer: 'Hoş görülmemiştir',
    difficulty: 2,
  },
  {
    guideId: 'isha',
    question: 'Yatsı namazının farzı kaç rekattır?',
    options: ['2 rekat', '3 rekat', '6 rekat', '4 rekat'],
    correctAnswer: '4 rekat',
    difficulty: 1,
  },
  {
    guideId: 'isha',
    question: 'Hanefî mezhebinde vitir namazının hükmü nedir?',
    options: ['Müstehaptır', 'Vaciptir', 'Farzdır', 'Sünnettir'],
    correctAnswer: 'Vaciptir',
    difficulty: 2,
  },
  {
    guideId: 'isha',
    question: 'Vitir namazı kaç rekattır?',
    options: ['1 rekat', '5 rekat', '2 rekat', '3 rekat'],
    correctAnswer: '3 rekat',
    difficulty: 1,
  },
  {
    guideId: 'isha',
    question: 'Yatsı vakti ne zaman başlar?',
    options: ['İmsak girince', 'Gece yarısı olunca', 'Güneş batınca', 'Şafak kaybolunca'],
    correctAnswer: 'Şafak kaybolunca',
    difficulty: 2,
  },
  {
    guideId: 'isha',
    question: 'Vitir namazı ne zaman kılınır?',
    options: [
      'Sabah namazından sonra',
      'Yatsının farzından sonra',
      'Akşam ile yatsı arasında',
      'Yatsının farzından önce',
    ],
    correctAnswer: 'Yatsının farzından sonra',
    difficulty: 2,
  },
  {
    guideId: 'isha',
    question: 'Vitir namazının üçüncü rekatında okunan dua hangisidir?',
    options: ['Sübhâneke', 'Tahiyyât', 'Kunut duası', 'Salli-Bârik'],
    correctAnswer: 'Kunut duası',
    difficulty: 2,
  },
  {
    guideId: 'isha',
    question: 'Yatsı farzında kıraat nasıl yapılır?',
    options: ['Yalnız son rekat sesli', 'Tamamı sessiz', 'İlk iki rekat sesli', 'Tamamı sesli'],
    correctAnswer: 'İlk iki rekat sesli',
    difficulty: 2,
  },
  {
    guideId: 'isha',
    question: 'Yatsı vakti ne zaman sona erer?',
    options: ['Güneş doğunca', 'Gece yarısı olunca', 'İmsak girince', 'Teravih bitince'],
    correctAnswer: 'İmsak girince',
    difficulty: 2,
  },
  {
    guideId: 'jumuah',
    question: 'Cuma namazının farzı kaç rekattır?',
    options: ['3 rekat', '4 rekat', '2 rekat', '6 rekat'],
    correctAnswer: '2 rekat',
    difficulty: 1,
  },
  {
    guideId: 'jumuah',
    question: 'Cuma namazından önce okunan konuşmanın adı nedir?',
    options: ['Kunut', 'Kamet', 'Hutbe', 'Tesbihat'],
    correctAnswer: 'Hutbe',
    difficulty: 1,
  },
  {
    guideId: 'jumuah',
    question: 'Cuma namazı hangi vakitte kılınır?',
    options: ['Öğle vaktinde', 'İkindi vaktinde', 'Sabah vaktinde', 'Kuşluk vaktinde'],
    correctAnswer: 'Öğle vaktinde',
    difficulty: 1,
  },
  {
    guideId: 'jumuah',
    question: 'Hutbe okunurken cemaat ne yapmalıdır?',
    options: [
      'Susup dinlemelidir',
      'Nafile kılmalıdır',
      "Kur'an okumalıdır",
      'Sesli tekbir getirmelidir',
    ],
    correctAnswer: 'Susup dinlemelidir',
    difficulty: 1,
  },
  {
    guideId: 'jumuah',
    question: 'Cuma namazını kılan kişi ayrıca öğle namazı kılar mı?',
    options: [
      'Ertesi gün kılar',
      'Kılmaz, Cuma yerine geçer',
      'Kılar, ikisi ayrıdır',
      'Yalnız iki rekat kılar',
    ],
    correctAnswer: 'Kılmaz, Cuma yerine geçer',
    difficulty: 1,
  },
  {
    guideId: 'jumuah',
    question: 'Cuma namazına yetişemeyen kişi ne kılar?',
    options: [
      'Öğle namazını dört rekat',
      'Cumayı tek başına iki rekat',
      'İkindi namazını erken',
      'Hiçbir şey kılmaz',
    ],
    correctAnswer: 'Öğle namazını dört rekat',
    difficulty: 2,
  },
  {
    guideId: 'jumuah',
    question: 'Cuma günü okunması tavsiye edilen sure hangisidir?',
    options: ['Kevser suresi', 'Bakara suresi', 'Kehf suresi', 'Nas suresi'],
    correctAnswer: 'Kehf suresi',
    difficulty: 2,
  },
  {
    guideId: 'jumuah',
    question: 'Cuma günü için tavsiye edilen hazırlık nedir?',
    options: [
      'Gusledip temiz giyinmek',
      'Öğleye kadar oruç tutmak',
      'Namaza kadar konuşmamak',
      'Hutbeden önce yemek',
    ],
    correctAnswer: 'Gusledip temiz giyinmek',
    difficulty: 1,
  },
];
